### ISSUE TITLE
Calendar thinks it's in mobile when initially server side rendering

### ISSUE THREAD

**Issue by coffenbacher** [coffenbacher/calendar#2]
![image](https://cloud.githubusercontent.com/assets/245867/21254805/be9a8f86-c31c-11e6-8ca8-aae2b93409b3.png)

So the layout flips out a bit for a second on desktop until client-side React can reconcile it

**Comment by goto-bus-stop** [comment]
Hmmyeah. It's always going to either be wrong on mobile by default, or on desktop, with how it's currently done. Since the DOM is different between mobile and desktop. I think to remove the jump entirely, it'd have to only use CSS media queries to differ between the layouts

**Comment by coffenbacher** [comment]
It would never be 100% accurate, but I'm pretty sure parsing the useragent when it's rendering server-side would work for the vast majority of cases, haven't looked to see if/how that's possible yet with how it's setup though

**Comment by goto-bus-stop** [comment]
True. Could use https://www.npmjs.com/package/device, I think, in a getInitialProps() method:

```js
import device from 'device'

getInitialProps ({ req }) {
  return { isMobileAgent: req && device(req.userAgent).is('mobile') }
}
```

and then in the `<Media />` callback in https://github.com/coffenbacher/calendar/blob/master/components/MatchList.js, check for both the Media parameter and the isMobileAgent prop.

```js
<Media query={mobileBreakpoint}>
  { matches => if (matches || isMobileAgent) ... }
</Media>
```

I can give this a shot later tonight i think

**Comment by coffenbacher** [comment]
Awesome! That looks promising indeed. I am working on #4 at the moment so have at it if you want.
