### ISSUE TITLE
iCal export

### ISSUE THREAD

**Issue by happyleavesaoc** [coffenbacher/calendar#3]
Would be great to have an endpoint giving an iCal format (ics) file. This node package should do it: https://www.npmjs.com/package/ics

Then you could integrate this data into other calendar systems, like Google Calendar or Outlook.

**Comment by coffenbacher** [comment]
Great idea! I'm working on a bit of a rewrite to experiment with some stuff, I will include that. Multiple endpoints has always been the goal, and that's a great suggestion

**Comment by happyleavesaoc** [comment]
Exporting individual events is nice. Is it possible to produce an `ics` or similar that is dynamically updated with *all* events? That way it can be imported into Google Calendar and events would continually show up. Right now manual intervention is required.

**Comment by coffenbacher** [comment]
I'll look into it here: https://github.com/coffenbacher/calendar/issues/14
